version: '3.7'

volumes:
  database:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  workspace:
    driver: ${VOLUMES_DRIVER}
  nginx:
    driver: ${VOLUMES_DRIVER}
  phpfpm:
    driver: ${VOLUMES_DRIVER}
  worker:
    driver: ${VOLUMES_DRIVER}

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# Define services
# Uncomment ports if you will not use override file
services:

  ### Database Container #################################
  database:
    build:
      context: ./docker/database
      args:
        - TZ=${WORKSPACE_TIMEZONE}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/storage/database:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    #ports:
      #- 3306:3306
    networks:
      - backend

  ### Redis Container #########################################
  redis:
    build:
      context: ./docker/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./docker/storage/redis:/data
    sysctls:
      - net.core.somaxconn=65535
    #ports:
      #- 6379:6379
    networks:
      - backend

  ### Workspace Container ###############################
  workspace:
    tty: true
    build:
      context: ./docker/workspace
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./src:/home/app/src:delegated
    depends_on:
      - database
      - redis
    networks:
      - backend
    links:
      - database
      - redis

  ### Nginx Container ###############################
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
      - ./src:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    #ports:
      #- 80:80
      #- 443:443
    depends_on:
      - phpfpm
    networks:
      - backend
    links:
      - phpfpm

  ### PHPFPM Container ###############################
  phpfpm:
    build:
      context: ./docker/phpfpm
      args:
        - PUID=${PUID}
        - TZ=${WORKSPACE_TIMEZONE}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
    volumes:
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    #ports:
      #- 9000
    depends_on:
      - database
      - redis
    networks:
      - backend
    links:
      - database
      - redis

  ### PHP Worker Container ###############################
  worker:
    build:
      context: ./docker/worker
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./src:/var/www/html
      - ${WORKER_LOG_PATH}:/var/log/supervisord
      - ./docker/worker/supervisord.d:/etc/supervisord.d
    #ports:
      #- 9001:9001
    depends_on:
      - database
      - redis
    networks:
      - backend
    links:
      - database
      - redis